apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-service
spec:
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
    spec:
      containers:
        - name: dispatcher-service
          image: dispatcher-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                # wait for 5s before sending SIGTERM to pod
                command: [ "sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9003
          env:
            - name: BPM_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888
            - name: SPRING_RABBITMQ_HOST
              value: polar-rabbitmq