apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-service
spec:
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9003"
    spec:
      containers:
        - name: dispatcher-service
          image: dispatcher-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                # wait for 5s before sending SIGTERM to pod
                command: [ "sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9003
          env:
            - name: BPM_JVM_THREAD_COUNT
              value: "50"

          livenessProbe:
            httpGet:
              port: 9003
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 9003
              path: /actuator/health/readiness
            initialDelaySeconds: 20
            periodSeconds: 15